name: simple-pages
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: foxbits/simple-pages:latest
    container_name: simple-pages
    environment:
      - NODE_ENV=production
    ports:
      - 9821:3000
    restart: unless-stopped